calendrier:
    path:    /
    defaults: { _controller:"SCGeneralBundle:Examen:calendrier" }
examen:
    path:     /{id}
    defaults: { _controller: "SCGeneralBundle:Examen:index" }

examen_show:
    path:     /{id}/show
    defaults: { _controller: "SCGeneralBundle:Examen:show" }

examen_new:
    path:     /new
    defaults: { _controller: "SCGeneralBundle:Examen:new" }

examen_create:
    path:     /create
    defaults: { _controller: "SCGeneralBundle:Examen:create" }
    methods:  POST

examen_edit:
    path:     /{id}/edit
    defaults: { _controller: "SCGeneralBundle:Examen:edit" }

examen_update:
    path:     /{id}/update
    defaults: { _controller: "SCGeneralBundle:Examen:update" }
    methods:  [POST, PUT]

examen_delete:
    path:     /{id}/delete
    defaults: { _controller: "SCGeneralBundle:Examen:delete" }
    methods:  [POST, DELETE]
