<?php

namespace SC\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SosRepository extends EntityRepository
{
}
